version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    AWS_ACCOUNT_ID: "374553884378"
    IMAGE_REPO_NAME: "fargate-ecr"
    IMAGE_TAG: build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - apt-get update -y && apt-get install jq -y
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_REPO_NAME: "fargate-ecr"
      - IMAGE_TAG: build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - tmp=$(mktemp) && SHA=$(docker inspect $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest | jq -c '.[0].RepoDigests' | sed 's/[][]//g' | sed 's/"//g') && jq -r --arg SHA "$SHA" '.Resources.TaskDefinition1.Properties.ContainerDefinitions[0].Image=$SHA' ecs-taskdefinition-service-uat.json > "$tmp" && mv -f "$tmp" ecs-taskdefinition-service-uat.json
      - cat ecs-taskdefinition-service-uat.json
artifacts:
  files:
    - ecs-taskdefinition-service-uat.json
  discard-paths: yes
